# Generated by Django 4.2.1 on 2023-05-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id_test', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('login', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=45)),
                ('user_second_name', models.CharField(max_length=45)),
                ('user_father', models.CharField(max_length=45)),
                ('user_group', models.CharField(max_length=45)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.users')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=45)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id_ans', models.IntegerField(primary_key=True, serialize=False)),
                ('user_answer', models.CharField(max_length=45)),
                ('id_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questions')),
                ('users_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.users')),
            ],
        ),
    ]
