# Generated by Django 4.2.1 on 2023-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_answers_users_id_user_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='id_question',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
