# Generated by Django 4.2.1 on 2023-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_alter_questions_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id_ans',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
