# Generated by Django 4.2.1 on 2023-05-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_alter_answers_users_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='users_id_user',
            new_name='userInfo',
        ),
    ]
