# Generated by Django 4.2.1 on 2023-05-22 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0009_rename_userinfo_answers_users_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.userpersonalinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='users_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
